### ISSUE TITLE
meteologix.com

### ISSUE THREAD

**Issue by MD55DM** [bogachenko/fuckfuckadblock#198]
### Basic information

**Check the link:** `https://meteologix.com/it`
**Category:** Anti-adblock
**Reported from:** Italy

### User environment

**Browser:** Chrome 91.xx
**Extension or program:** Adguard
**DNS:** No DNS

**Comment by bogachenko** [comment]
> Extension or program: Adguard

Adguard What? Adguard for Windows? Adguard for Mac? Adguard for Android?

**Comment by MD55DM** [comment]
Ops, sorry for incomplete informations.

I'm using Adguard for windows (latest version with updated list (to be sure, forced update right now and verified that your list is up to date).
I'm also using AdGuard DNS


Tested https://meteologix.com/it with latest update but I immediately get the Adblock warning https://meteologix.com/it/site/adblockuser/3

Thanks for your help attempt!

**Comment by bogachenko** [comment]
>I'm also using AdGuard DNS
>DNS: No DNS
>Ops, sorry for incomplete informations.

_The paragraph in the markup about the presence of DNS, which you had to fill out, was there for a reason._
Your problem is filtering DNS. Such DNS causes problematic triggers. Addresses that block with the help of a DNS server are advertising, they are used by site administrators, some of these addresses need to be unblocked (if we are talking about a site - `meteologix.com`, there's only one - `md-nx.com`, but it is blocked by you, since you use Adguard DNS) to hide the anti-block notification.

2 ways.

1. Give up such DNS if you want to hide anti-adblock notifications.
or
2. Use a browser extension, sometimes it helps, but not always.

**Comment by MD55DM** [comment]
A Big thanks for your help and sorry for wasting your time. I switched to Google DNS and now meteologix.com load and run fine. Thanks again!
