### ISSUE TITLE
adyou.me

### ISSUE THREAD

**Issue by heismauri** [bogachenko/fuckfuckadblock#233]
### Basic information

**Check the link:**  `http://adyou.me/8Zi2`
**Category:** Anti-adblock
**Reported from:**  Chile

### User environment

**Browser:**  Brave, latest
**Extension or program:**  Brave Shield
**DNS:**  1.1.1.1 Cloudfare
**Extensions:**  HTTPS Everywhere, Fastforward

**Comment by bogachenko** [comment]
>Extension or program: Brave Shield

Not supported (It is my fault that I did not add this to the article https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#unsupported-and-semi-supported-products I'll write there soon, but in fairness, people have already created a topic with a detailed program https://github.com/bogachenko/fuckfuckadblock/issues/84), my project only works with [uBlock Origin](https://github.com/gorhill/uBlock) or [Adguard](https://adguard.com/).

So, in order to use my project, disable Brave Shield and install ONE of the extensions listed above and after installation, subscribe to the list again, and then recheck the site.

**Comment by bogachenko** [comment]
BTW - https://github.com/bogachenko/fuckfuckadblock/wiki/Installation-instruction
