### ISSUE TITLE
adikinfo.my.id

### ISSUE THREAD

**Issue by rigaz29** [bogachenko/fuckfuckadblock#234]
### Basic information

**Check the link:**  `https://adikinfo.my.id/secret-of-various-benefits-of-watercress-for-health/?id=REJiK0N5c3dQMkpEa25xcGh4c3NteDhBdUxtNlZwZ0lvdDFsb1hJYkw3VTVwOVZsSTQ5WFJQRVM5ODNzSWZtN0RaVjRNM2NBNEpRZDNBQWh4cWhsV1ExWlNOaTdZcTlTdldxWkNvdjE0L0k9`
**Category:** Anti-adblock
**Reported from:**  Indonesia

**Comment by bogachenko** [comment]
https://github.com/bogachenko/fuckfuckadblock/blob/d141def78372c4fdb14029faa32e7f87a8cfa49c/fuckfuckadblock.txt#L448
Regex, which has been on my list for a hundred years, works fine and removes this banner.
but you didn't fill out the form, and I won't guess which extension/browser you use.
I can only advise you to restore the default settings and clean the cookies, the problem is blocking the script `https://ads.maskoding.com/ads.js`
