### ISSUE TITLE
megaup.net

### ISSUE THREAD

**Issue by ChaoticHolon** [bogachenko/fuckfuckadblock#268]
### Basic information
**Check the link:** `https://megaup.net/1I951/Testing_1_2_3.txt`
**Category:** Anti-adblock
**Reported from:** US

### User environment

**Browser:** Vivaldi 5.1.2567.39 (Stable channel) (64-bit) 
**Extension or program:** uBlock Origin
**DNS:** Cloudflare
**Extensions:** Privacy, Dark Reader, Decentraleyes, FastForward, BetterTTV, TTV LOL, Private Internet Access, Sci-Hub X Now!, MBFC, FB Purity, Cookie AutoDelete, Reddit Enhancement Suite, Augmented Steam, Session Buddy, Bypass Paywalls, SponsorBlock

### Additional message
As I use a lot, naturally tried disabling extensions. 'Disable Adblock' message disappears and the countdown timer shows up and eventually 'Create Download Link' as expected as soon as uBlock is disabled and page is refreshed. Returns the instant it is enabled and refreshed. Was working for a while after your recent fix, now seems to be getting popped by regular uBlock rules even with this list disabled.

**Comment by bogachenko** [comment]
I can not reproduce, everything works for me. Clear your cookies/reinstall the extension or try a different browser. 

> Cookie AutoDelete

Causes triggers on some crappy sites, due to the fact that advertising or tracker cookies have not been installed. In short, breaks my list, on some sites. 

> Decentraleyes

Not about this site, the extension blocks various "free" CDNs (often ad-supported) that I or other people allow to hide the ad blocking notice. In short, breaks my list, on some sites. 

> Privacy

Its [Privacy Badger](https://privacybadger.org/)? Read here https://github.com/bogachenko/fuckfuckadblock/wiki/Problematic-extensions

> Bypass Paywalls

Haven't, but I doubt using it with uBO is a good idea.

> SponsorBlock

Come on, you're already using uBO. That's enough.

***
You have many extensions protecting your privacy. Ha-ha.
Please read this https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#known-issues

In this sheet, I add some trackers and ads to the exception in order to bypass the notification about ad blockers, this is not compatible, and decide for yourself what is more important to you - your privacy or access to sites?

PS: For information, the vivaldi browser is not private at all.
