### ISSUE TITLE
infinityblogger.in

### ISSUE THREAD

**Issue by xd003** [bogachenko/fuckfuckadblock#273]
### Basic information

**Check the link:** `https://www.infinityblogger.in/`
**Category:** Anti-adblock
**Reported from:** India 

### User environment

**Browser:** Edge v98.0.1108.56
**Extension or program:** Only uBlock Origin 
**DNS:** Yes , i am using Nextdns 
**Extensions:** Ublock origin , bitwarden , SponsorBlock , Fastforward 

Opening the mentioned link detects the adblocker and prompts for it to be disabled before proceeding further

**Comment by bogachenko** [comment]
>Nextdns

>Blocking by DNS with AdGuard for Windows/Mac/Android and uBlock Origin

https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#unsupported-and-semi-supported-products

**Comment by bogachenko** [comment]
Refuse to use a filtering DNS server or refuse to use my list.

PS: also if you use uBlock Origin, then you don't need the SponsorBlock extension anymore.

**Comment by xd003** [comment]
> > Nextdns
> 
> > Blocking by DNS with AdGuard for Windows/Mac/Android and uBlock Origin
> 
> https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#unsupported-and-semi-supported-products
> 
> I'm tired of repeating already (I'll have to create a separate page on the Wiki) - Fuck Fuckadblock and filtering DNS servers (which block ads) are not compatible things.
> 
> The rule that is already on my list, here it is `||googleads.g.doubleclick.net/pagead/id^$xmlhttprequest,redirect-rule=nooptext` removes this anti-adblock, but due to the fact that the `doubleclick.net` domain is blocked by DNS, it will not work for you.

Thanks for the heads up , i have disabled Nextdns and its loading well now , my bad  . On other note , do you think its a good idea if i whitelist all the advertising domains in your list in Nextdns so as to have both system level ad blocking and proper anti adblock with ublock in browsers ?

**Comment by xd003** [comment]
Thanks for all the suggestions , i am personally trying to find a way using which i can disable dns level adblockers only for the browser and have it work systemwide elsewhere so that can enjoy best of both worlds ie. system level adblocking + proper antiadblock & blocking with ubo in browsers . I hope there must be some dns client out there which can whitlist apps :)

**Comment by bogachenko** [comment]
>do you think its a good idea if i whitelist all the advertising domains in your list in Nextdns so as to have both system level ad blocking and proper anti adblock with ublock in browsers ?

Definitely a bad idea.

First, the meaning of such a DNS is lost. DNS blocking is the last century and you need to use it, only where the detailed blocking is not possible (I personally bought Raspberry Pi 4, I installed the [Adguard Home](https://github.com/AdguardTeam/AdGuardHome) package and I filter network requests for an Android TV Box and a tablet, there I use my own [black](https://raw.githubusercontent.com/bogachenko/filterlist/main/bogachenkoBL.dns) and [white](https://raw.githubusercontent.com/bogachenko/filterlist/main/bogachenkoWL.dns) sheets). 

Secondly, errors will still occur (I use a couple of sites on a Tablet or an adnroid TV Box, and there are much more on a computer, respectively, and there will be more errors), because it is not possible to predict which site will use certain domains with advertising to catch a user with an ad blocker. Although of course they have no creativity, and often the same sites are used.

**Comment by bogachenko** [comment]
Although you can try VPN for encryption, then DNS blocking in the browser will not work, because your traffic in the browser will be encrypted, and the rest of the traffic will not. Enjoy - https://www.torproject.org/
