### ISSUE TITLE
radenku.com

### ISSUE THREAD

**Issue by rigaz29** [bogachenko/fuckfuckadblock#291]
### Basic information

**Check the link:**  `https://radenku.com/cara-install-openclash-openwrt-di-semua-router/`
**Category:** Anti-adblock
**Reported from:**  Indonesia

### User environment

**Browser:**  Firefox latest
**Extension or program:**  Ublock Origin latest

**Comment by bogachenko** [comment]
I can only reproduce this if I add a blocking rule for this site `||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=radenku.com,important`, but my rule `@@/^https?:\/\/(www\.)?[^\s]+\/ad[svbxo]?[-_]?[a-z]{1,15}\.js/$xmlhttprequest` works fine and bypasses this script so I don't have any adblock disable notice. The problem is on your side, something is blocking this request.

**Comment by bogachenko** [comment]
I'll add a simple-general CSS rule that doesn't seem to break anything, but in principle, as I said, it's superfluous, since the rule above works with a BANG.
