### ISSUE TITLE
AdAway support

### ISSUE THREAD

**Issue by KevinNitroG** [bogachenko/fuckfuckadblock#399]
### Additional message

Excuse me can you make it compatible with adaway on rooted phone? Thank you

**Comment by bogachenko** [comment]
It is impossible to do in principle at all, with any list for adblock. The reason is a completely different principle of work.

[Adaway](https://adaway.org/) uses the syntax similar to the [Hosts.txt](https://ru.wikipedia.org/wiki/Hosts) file, and it doesn’t matter which method of work is chosen in the program for this program - VPN or, in your case, root.
**In short, this program blocks only [domain names](https://en.wikipedia.org/wiki/Domain_name)** () and it is impossible to block any specific or necessary script that triggers a trigger on a particular site using this program and most importantly, this program does not support [scriptlets](https://github.com/AdguardTeam/Scriptlets), without which my list will not work..

eg.

good
```
||google.com^
0.0.0.0 google.com
127.0.1 google.com
```
bad
```
||google.com/images/errors/robot.png
||google.com/js/bg/SuMlUhX4cPM12D0RgbbRD7Tv2WwOtI2jbRi1pJ228y0.js
```
If you have root, I suggest using [Adguard for Android](https://adguard.com/en/adguard-android/overview.html) (but keep in mind that 2 or more ad blockers will cause false positives on the page, in addition, Adguard for Android has a built-in DNS blocker).
Speaking of advertising, where luck may smile at you => [PUSH ME](https://4pda.to/forum/index.php?showtopic=275091&st=1620#entry34876590), if the site uses third-party advertising domains on the site, then for sites where there are anti-block and pop-ups - no. Because it is built into the main page of the site, or on a certain JS of this site.
PS: the program is paid, I paid 1 time and forgot.
