### ISSUE TITLE
bg-gledai.live

### ISSUE THREAD

**Issue by Rusenche** [bogachenko/fuckfuckadblock#401]
### Basic information

**Check the link:**  `https://www.bg-gledai.live/online-btv-action`
**Category:** Anti-adblock
**Reported from:** 

### User environment

**Browser:**  Ungoogled Chromium v.108.0.5359.125 x64
**Adblocker:**  uBlock Origin v.1.47.4
**Extensions:** 
**DNS:**  `https://dns.adguard-dns.com/dns-query`

**Comment by bogachenko** [comment]
>DNS: https://dns.adguard-dns.com/dns-query

https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#blocking-by-dns-with-adguard-for-windowsmacandroid-and-ublock-origin

**Comment by bogachenko** [comment]
>DNS: https://dns.adguard-dns.com/dns-query

https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#blocking-by-dns-with-adguard-for-windowsmacandroid-and-ublock-origin

The problem is not in my list, but that you use 2 ad blockers (DNS blocker from AdGuard and u Black Origin), read the page and understand that you do not need to do this. There will always be false positives, problems are on your side.

There is a script installed on your Bulgarian website that monitors the blocking of a text request https://pagead2.googlesyndication.com/pagead/js/adsbygoogle .js, if DNS from AdGuard blocks this request, and then it is resolved in my list, then a conflict arises, so the site understands that you are using an adblock.
***
please **don't upload images here!**

**Comment by Rusenche** [comment]
> > DNS: https://dns.adguard-dns.com/dns-query
> please **don't upload images here!**

:| But then for me at this stage a more hassle free solution is to turn off your filter and the site loads without issue!

**Comment by Rusenche** [comment]
However, I deliberately decided to test your point without you having actually checked what you wrote yourself.

1. I removed https://dns.adguard-dns.com/dns-query.
2. I restarted Windows.
3. I started Windows.
4. I ran Ungoogled Chromium v.108.0.5359.125 x64.
5. I activated your https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt
6. I updated all filters in uBlock Origin v.1.47.4.
7. I loaded https://www.bg-gledai.live/online-btv-action.
8. You're not allowing photos to be uploaded here, so I can show you that it's your filter that's the problem.

And again the site https://www.bg-gledai.live/online-btv-action shows a window for adblock detect and to turn off my adblocker.

9. I turn off your https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt and the site https://www.bg-gledai.live/online-btv-action starts normally.

Conclusion: I leave it to you, but you were quick to close this thread even without any test... It's elementary things, but a man, when he gets stuck that the problem is somewhere else, not in his own filter...

**Comment by bogachenko** [comment]
I don't know why you are behaving like this, but for your comfort, I recorded a video `https://imgur.com/a/x38IZw0`, check it out. If the problem is still "because of my list", so be it.

Also, this is another mirror here, redirecting from bg-gledai.live to bg-gledai.co

**Comment by Rusenche** [comment]
> Also, this is another mirror here, redirecting from `bg-gledai.live` to `bg-gledai.co`, now I will add a commit for this mirror.

It is now working and the problem is fixed.

Thanks.
