### ISSUE TITLE
getautoclicker.com

### ISSUE THREAD

**Issue by KaKi87** [bogachenko/fuckfuckadblock#408]
### Basic information

**Check the link:** `https://stable.getautoclicker.com/`
**Category:** Anti-adblock
**Reported from:** France

### User environment

**Browser:** Brave 1.49.128
**Adblocker:** uBlock Origin 1.48.4
**Extensions:** LibRedirect, 'Improve YouTube!' (BETA), Auto Clicker - AutoFill, BetterTTV, Copy Link Text, Dark Reader, Free Download Manager, JSON Viewer, Nimbus Screenshot & Screen Video Recorder, Quick Javascript Switcher, Redirect Path, Redirector, Refined GitHub, SponsorBlock for YouTube - Skip Sponsorships, Stylus, uBlock Origin, Vencord Web, Violentmonkey, Vue.js devtools
**DNS:** Quad9 (9.9.9.9)

### Additional message

I also wrote the following JS code to be executed in `chrome://extensions` in order to export the extension list, if you'd want to reuse it :

```js
console.log([
    ...document
        .querySelector('extensions-manager')
        .shadowRoot
        .querySelector('#items-list')
        .shadowRoot
        .querySelectorAll('extensions-item')
].map(element => `[${
        element
            .shadowRoot
            .querySelector('#name')
            .textContent
    }](https://chrome.google.com/webstore/detail/${
        element
            .shadowRoot
            .querySelector('#extension-id')
            .textContent
            .slice(4)
    })`
).join(', '));
```

---

Thanks

**Comment by bogachenko** [comment]
>Extensions: LibRedirect, 'Improve YouTube!' (BETA), Auto Clicker - AutoFill, BetterTTV, Copy Link Text, Dark Reader, Free Download Manager, JSON Viewer, Nimbus Screenshot & Screen Video Recorder, Quick Javascript Switcher, Redirect Path, Redirector, Refined GitHub, SponsorBlock for YouTube - Skip Sponsorships, Stylus, uBlock Origin, Vencord Web, Violentmonkey, Vue.js devtools

I can't reproduce which of your extensions is blocking access to the `googlesyndication.com` domain (which is allowed in my list), disable all extensions, leaving only the uBO ad blocker and check.
_I will not export your list of extensions, it's just impolite + impossible to please everyone, you should make sure that the problem is in the blocker before sending the report - check on a clean browser without extensions, when you filled out the report, there was a link to the instruction in the markup https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#before-sending-a-report for such cases, which I didn't just put in._

>Browser: Brave 1.49.128

Also, I bet that using this unscrupulous browser you have not disabled the built-in ad blocker, which you need to do first of all when using my sheet. Because using 2 or more ad blockers is unacceptable, there will be false positives. Instructions for the browser are here https://github.com/bogachenko/fuckfuckadblock/issues/404#issuecomment-1478919302

PS: please do not upload images here.

**Comment by KaKi87** [comment]
> disable all extensions, leaving only the uBO ad blocker and check

Even better, I created a new browser profile and only enabled uBO, Fuck Fuckadblock and the Auto Clicker extension : I confirm I'm still reproducing the issue.

> when you filled out the report, there was a link to the instruction in the markup

I'm sorry I didn't notice it as I'm using a WYSIWYG editor when filling issues.

I would like to recommend moving this to a `CONTRIBUTING.md` file, which would be highlighted by GitHub when filling issues for the first time and always displayed below the form as well :

| ![Screenshot from 2023-04-06 03-52-40](https://user-images.githubusercontent.com/21284089/230252878-be7c8c6b-1241-44b0-b65b-da127e9482e7.png) | ![Screenshot from 2023-04-06 03-49-58](https://user-images.githubusercontent.com/21284089/230252906-049443e1-be97-4d5f-88ba-ab7082968682.png) |
| --- | --- |

> I bet that using this browser you have not disabled the built-in ad blocker

As a matter of fact I did, it's the first thing I do when installing the browser (as well as disabling all the cryptocurrency stuff I don't care about).

And I obviously did it when creating the new profile as well.

> PS: please do not upload images here.

I suppose you meant ad-related screenshots, I hope you don't mind my screenshots illustrating the benefits of a `CONTRIBUTING.md` file.

---

Thanks

**Comment by bogachenko** [comment]
>I suppose you meant ad-related screenshots, I hope you don't mind my screenshots illustrating the benefits of a CONTRIBUTING.md file.

don't upload **_any_** images here, please.

>As a matter of fact I did, it's the first thing I do when installing the browser (as well as disabling all the cryptocurrency stuff I don't care about).

step by step how exactly did you disable the built-in ad blocker?

did you change something in the hosts.txt file, banned domains there? Do you have an antivirus? Can you check with another browser?

**Comment by KaKi87** [comment]
> don't upload any images here, please.

Ok, why though ?
GitHub gives to everyone the right to upload images everywhere the button is present. :thinking: 

> step by step how exactly did you disable the built-in ad blocker?

1. Go to `brave://settings/shields` ;
2. Select *Disabled* for *Trackers & ads blocking* ;
3. Select *Disabled* for *Block fingerprinting*.

> did you change something in the hosts.txt file, banned domains there? Do you have an antivirus?

I do not. I'm on Linux, by the way.

> Can you check with another browser?

The Auto Clicker extension is only available on Chromium-based browsers.

> Go to uBO settings on the - `Support` tab, scroll down and copy the `Troubleshooting` field. Paste it here.

```
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 93451
  cosmetic: 40218
  scriptlet: 34671
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24126-12, now
  default: 
    user-filters: 0-0, never
    easylist: 65159-51, now
    easyprivacy: 30788-1177, now
    plowe-0: 3753-936, now
    ublock-abuse: 78-1, now
    ublock-badware: 6301-124, now
    ublock-filters: 33376-2696, now
    ublock-privacy: 302-2, now
    ublock-quick-fixes: 485-134, now
    ublock-unbreak: 1960-45, now
    urlhaus-1: 7368-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2353 ms
  maxAssetCacheWait: 22 ms
```

**Comment by bogachenko** [comment]
>The Auto Clicker extension is only available on Chromium-based browsers.

It is not necessary to check with a different engine, Chromium, Google Chrome, Vivaldi is an another browser, it is an another browser.

>GitHub gives to everyone the right to upload images everywhere the button is present.

Cool, happy for them. I'm not five years old, I don't need a book/forum with beautiful pictures. The lack of privacy and cluttering of the Issues tab with images is confusing, everything that can be said in language does not have to be shown.
***
Does it work?
`@@||getautoclicker.com^$generichide`
`||pagead2.googlesyndication.com^$important,script,redirect=googlesyndication_adsbygoogle.js,domain=getautoclicker.com`

**Comment by KaKi87** [comment]
> It is not necessary to check with a different engine, Chromium, Google Chrome, Vivaldi. Another browser is another browser.

I confirm I'm reproducing the issue on frenchly installed Chromium.

> On Linux, everything that I have listed is also available.

Except antiviruses, because it doesn't don't need these ;)

> something you still does not allow the domain from Google to work

I'm sorry I should have mentioned that I'm not using the Quad9 DNS directly but through AdGuard Home (a local network DNS filter, like PiHole), which indeed blocks the domain you mentioned.

If I make my computer connect to Quad9 directly, thus unblocking the domain, and no anti-adblock dialog indeed appears.

**Comment by bogachenko** [comment]
If for this site, then `stable.getautoclicker.com##+js(nostif, (), adsLoaded)`
***
If for other sites (such false positives are not uncommon, and sometimes they cannot be bypassed at all)

I don't know a way => https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#blocking-by-dns-with-adguard-for-windowsmacandroid-and-ublock-origin

You can try to use VPN, isolate the right application, say Brave, so that it only has access through the VPN, and the system/other programs are directly. Thus, the browser will give an encrypted answer and the domain will not be blocked. Nevertheless, I do not quite understand why, damn it, do you need it at all? Blocking by DNS is necessary only where there is no accurate lock, it is an outdated method of locking. I myself use Adguard Home for TV (for Android console), and why use it on the computer I have no explanation.

**Comment by KaKi87** [comment]
> If for this site, then `stable.getautoclicker.com##+js(nostif, (), adsLoaded)`

I'm afraid this doesn't work :/

> You can try to use VPN

This is overkill, I guess I'm just going to connect to Quad9 directly on this computer, it should be fine since I'm on Linux.

> [bogachenko/fuckfuckadblock/wiki/Support-policy#blocking-by-dns-with-adguard-for-windowsmacandroid-and-ublock-origin](https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#blocking-by-dns-with-adguard-for-windowsmacandroid-and-ublock-origin)

The reason why I'm using a third-party DNS is to bypass censorship.
And the reason why I'm using Quad9 is not to give even more data to Google or CloudFlare.

> I do not quite understand why, damn it, do you need it at all?

Just like you, I too have an Android TV device.
Additionally, I have a Windows dual boot, which, as rarely as I use it, needs DNS-based ad blocking for UWP apps.
To finish, I also have some IoT devices.

**Comment by bogachenko** [comment]
>needs DNS-based ad blocking for UWP apps

I recommend to pay attention to the Adguard for Windows https://adguard.com/en/adguard-windows/overview.html

>The reason why I'm using a third-party DNS is to bypass censorship.
> And the reason why I'm using Quad9 is not to give even more data to Google or CloudFlare.

>Blocking by DNS is necessary only where there is no accurate lock, it is an outdated method of blocking. I myself use Adguard Home for TV, [eg1](https://github.com/bogachenko/filterlist/blob/main/bogachenkoBL.dns) and [eg2](https://github.com/bogachenko/filterlist/blob/main/bogachenkoWL.dns) (for Android console), and why use it on the computer I have no explanation.

The article I provided ONLY talks about filtering queries by DNS (aka DNS Ads-Filtering). There are no objections to third-party services that do not block ads from Google or CloudFlare.

>I'm afraid this doesn't work :/

`stable.getautoclicker.com##+js(nostif, adsLoaded)` minor mistake

**Comment by KaKi87** [comment]
> I recommend to pay attention to the Adguard for Windows [adguard.com/en/adguard-windows/overview.html](https://adguard.com/en/adguard-windows/overview.html)

I know about it, but it's proprietary.

> The article I provided ONLY talks about filtering queries by DNS (aka DNS Ads-Filtering). There are no objections to third-party services that do not block ads from Google or CloudFlare.

The article you linked says : `switching the automatic DNS received from your Internet provider to third-party DNS resolvers, even to non-filtering ones, for example from Google or from Cloudflare, can have an extremely negative impact on your work on the Internet.`
That's what I was replying to.

> `stable.getautoclicker.com##+js(nostif, adsLoaded)`

That works, thanks !
Will you add it to the blocklist ?

**Comment by bogachenko** [comment]
>The article you linked says : switching the automatic DNS received from your Internet provider to third-party DNS resolvers, even to non-filtering ones, for example from Google or from Cloudflare, can have an extremely negative impact on your work on the Internet.
>That's what I was replying to.

I know what it says, because I wrote it. The second paragraph is about "it will negatively affect your Internet", it's about speed, you can say as an additional remark/precaution (its need to mark this part in italics in the Wiki for clarity). Your business, of course, is only to the first paragraph, since you deployed a home, ad-blocking DNS server and used it on a computer where there is no special need for this (especially on Linux, in my opinion), and this is what the article is about.

>I know about it, but it's proprietary.

I know. But the program is good (although there are drawbacks).

>Will you add it to the blocklist ?

I don't usually add that. The address causing the anti block trigger is already allowed in my list, the precaution of using 2 blockers (DNS ad-blocking and uBlock Origin) I've introduced you.
