### ISSUE TITLE
leoweekly.com

### ISSUE THREAD

**Issue by cartben656** [bogachenko/fuckfuckadblock#470]
### Basic information

**Check the link:** `https://www.leoweekly.com/2023/12/get-a-grip-santas-against-gun-violence-thoughts-from-a-louisville-santa/`
**Category:** Anti-adblock
**Reported from:** 

### User environment

**Browser:** 
**Adblocker:** 
**Extensions:** 
**DNS:** 

### Additional message

detctrs ublock origin

**Comment by cartben656** [comment]
wy thnbs dwn

**Comment by bogachenko** [comment]
The information that is missing and that you did not fill in in the markup does not let me reproduce your issue.

**Comment by cartben656** [comment]
browser chrome
adocker ulock origin 1.54.0
i use this wonerful liest plus https://github.com/bogachenko/filterlist plz nrna ulok origin sutff
i live in united state
i use ulock origin pluz paypl hony pluz winscribe vpn 
idk what dns is

sry

**Comment by cartben656** [comment]
oh an i use https://github.com/reek/anti-adblock-killer

**Comment by bogachenko** [comment]
>winscribe vpn

And where - to which country is it connected? As far as I know, this is not only a VPN, but also an ad blocker. 2 ad blockers - uBO and the winscribe solution cannot be used together, I wrote about this in the [instructions](https://github.com/bogachenko/fuckfuckadblock/wiki/Installation-instruction).

You probably also connected a third-party DNS server there, which is also [unacceptable](https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#vpn-programs-and-adguard-for-windowsmacandroid).

README
>https://adguard-dns.io/kb/general/dns-filtering/
>https://en.wikipedia.org/wiki/Domain_Name_System

Can you disable winscribe vpn and try without it? If the problem persists, then go to the uBO settings => Support tab => scroll down, there will be a "Troubleshooting" field, send me this field here in the comments.
***

>oh an i use https://github.com/reek/anti-adblock-killer

I doubt it very much. He is in the bathhouse at uBO (like me in general, lol), unless you have added additional characters to the URL, and if not, then in the settings of the uBO program you will have "0 used out of 0" displayed for reek/anti-adblock-killer

>i use this wonerful liest plus https://github.com/bogachenko/filterlist pluz normal ulok origin sutff

This is very unnecessary. I use very specific settings for sites there, there may be breakdowns for some of them. That repository is different from this one, because it was created mainly for personal use.

**Comment by cartben656** [comment]
i use isp dns then
winscribe remove
remve eek antiadblockikker and https://github.com/bogachenko/filterlist
still have issue

**Comment by bogachenko** [comment]
>If the problem persists, then go to the uBO settings => Support tab => scroll down, there will be a "Troubleshooting" field, send me this field here in the comments.

**Comment by cartben656** [comment]
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 102085
 cosmetic: 44003
 scriptlet: 19474
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 0-0, now
 default:
  user-filters: 4-0, never
  easylist: 75325-16, now
  easyprivacy: 33073-65, now
  plowe-0: 3776-1137, now
  ublock-badware: 7589-138, now
  ublock-filters: 35850-179, now
  ublock-privacy: 929-12, now
  ublock-unbreak: 2156-31, now
  urlhaus-1: 8425-1, now
  ublock-quick-fixes: 170-9, never
filterset (user): [array of 4 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4582 ms
 maxAssetCacheWait: 3162 ms


also i use edge not crhome sry

**Comment by bogachenko** [comment]
>https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 0-0, now

you do not use my filter, the readings `0-0, now` indicate this (advise you to familiarize yourself with [this](https://github.com/bogachenko/fuckfuckadblock/issues/423) topic). Delete the Fuck Fuck adblock and use the link `https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=raw` or SUBSRIBE button on the README.md file.

After the operation is completed, try again with the site.

**Comment by cartben656** [comment]
didnt reaize that installed but problems still there also updatd filer


my filters
! 2021-04-04 https://developer.chrome.com
developer.chrome.com##.hairline-top.cookie-banner

! 2021-04-07 https://stackoverflow.com
stackoverflow.com##.js-consent-banner.r16.l16.b16.bar-lg.fc-white.bg-black-750.p32.sm\:w-auto.ws4.z-nav-fixed.ps-fixed.ff-sans

! 2021-04-08 https://www.geeksforgeeks.org
www.geeksforgeeks.org##.show-consent.hide-consent.cookie-consent
www.geeksforgeeks.org##.side--container_wscard > [href^="https://premium.geeksforgeeks.org/premium-plans/"]



uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 108023
 cosmetic: 44526
 scriptlet: 36380
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=raw: 23168-2075, never
 default:
  user-filters: 4-0, never
  easylist: 75311-16, 1m
  easyprivacy: 33075-65, 1m
  plowe-0: 3777-1137, 1m
  ublock-badware: 7599-138, 1m
  ublock-filters: 35850-182, 1m
  ublock-privacy: 929-12, 1m
  ublock-quick-fixes: 180-9, 1m
  ublock-unbreak: 2157-31, 1m
  urlhaus-1: 10690-0, 1m
filterset (user): [array of 4 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1064 ms
 maxAssetCacheWait: 490 ms

**Comment by bogachenko** [comment]
I can't reproduce it-not on my phone, not on my main computer, not on a clean'n'virgin virtual machine. It's empty everywhere. The Internet is also empty, there were no similar problems - no one said that an antiadblock pop-up notification appeared on this site. I think the problem is on your side. Maybe you use some kind of antivirus or another program (which you may have forgotten to mention) to block one or the other.

Give me a screenshot to understand what it is and how it looks (I'll check in a couple of days, maybe I can reproduce it) - go to the site https://postimages.org / upload it there, select "Remove after 31 days" in the settings on the site and write a link here.

**Comment by bogachenko** [comment]
I would also be grateful if you [export](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog) the log of the network request inspector here.
