### ISSUE TITLE
userupload.net

### ISSUE THREAD

**Issue by nightznero** [bogachenko/fuckfuckadblock#476]
Helloz Bogachenko,

I came with question do You could block fake download buttons on `userupload.in`&`userupload.net` cuz I was trying by myself but everytimr its blocked and captchata preceed then window come with noticed of using adb.
here is 2e.x links that you could reproduce and block it
`userupload.in/pt13qw2tfypi`
`userupload.net/vro055faq4a1`
First appears right after entering the link,the second one shows up after making captcha and pressing blue button _create download link_
Heres is my trys of blocking but all are noticed by anti adb,one by one is more specific
`userupload.in##CENTER` -> `userupload.in##DIV.report` -> `userupload.in##A.btn.btn-danger[href='https://apkland.net/hotstar-adfree-apk/`
Best Regards, NIGHTZNERO.

**Comment by bogachenko** [comment]
It’s strange, but the site `userupload.net` does not open for me on any device. In addition, you are aware that my list only works for uBO and AdGuard <https://github.com/bogachenko/fuckfuckadblock/wiki/About-Fuck-Fuckadblock>, where these rules are already added, uBO has this `userupload.*##.btn-danger:has-text(/download/i)`, and AdGuard has this `userupload.*##.report > a.btn-danger`. What adblocker do you use? Is your Brave Shield disabled <https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#brave-shields>?

**please do not upload any images here**

**Comment by nightznero** [comment]
> @nightznero hello.
> 
> It’s strange, but the site `userupload.net` does not open for me on any device, I changed the ip address to different countries, it seems the domain has failed, but its mirror opens.. In addition, you are aware that my list only works for uBO and AdGuard https://github.com/bogachenko/fuckfuckadblock/wiki/About-Fuck-Fuckadblock, where these rules are already added, uBO has this `userupload.*##.btn-danger:has-text(/download/i)`, and AdGuard has this `userupload.*##.report > a.btn-danger`. What adblocker do you use? Is your Brave Shield disabled https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#brave-shields?
> 
> **please do not upload any images here**

I m Using AdGuard for Android,the browser is Brave but i use more browsers and everywhere that fake red button exists,on Brave shields is agressive adb enabled but with disabled adb in shield results are the same

**Comment by bogachenko** [comment]
>I m Using AdGuard for Android,the browser is Brave

Is the phone Rooted? Which sheets do you have installed and **enabled** in Adguard?

**Comment by nightznero** [comment]
> > I m Using AdGuard for Android,the browser is Brave
> 
> Is the phone Rooted? Which sheets do you have installed and **enabled** in Adguard?

All from ADG-mobile,Annoyances,popups+all language specific from them(not easylists language),all ublock-2020,LAN and so on + my list that fixes some False positives but there is nothing with _userupload.*_ sites

**Comment by bogachenko** [comment]
>Is the phone Rooted?

**Comment by nightznero** [comment]
> > Is the phone Rooted?

forgot to mention,no its not rooted

**Comment by bogachenko** [comment]
Having root rights is a prerequisite for using my list in the adguard for android program <https://github.com/bogachenko/fuckfuckadblock/wiki/Installation-instruction>, without them it will not work, just as cosmetic rules from the standard adguard base list (English) sheet will not work, in fact it do not work for you, since  , I already wrote above that the rule disabling the red button is already in the standard sheet from adguard.  Without root rights to Androi (you can delete my list), only domains are blocked, and even then not in all programs.

**Comment by bogachenko** [comment]
Having root rights is a prerequisite for using my list in the adguard for android program <https://github.com/bogachenko/fuckfuckadblock/wiki/Installation-instruction>, without them it will not work, just as cosmetic rules from the standard adguard base list (English) sheet will not work. In fact it do not work for you, since, I already wrote above that the rule disabling the red button is already in the standard sheet from adguard.  Without root rights to Android (you can delete my list), only domains are blocked, and even then not in all programs.
