### ISSUE TITLE
megaup.net

### ISSUE THREAD

**Issue by dandud100** [bogachenko/fuckfuckadblock#498]
Basic information
Check the link: https://megaup.net/25a7befd2a37f8e3409b7391b75be4d4/neu_10.txt
Category: Breakage
Reported from: Germany

User environment
Browser: Chrome
Adblocker: uBlock Origin
Extensions: None
DNS: 1.1.1.1

**Comment by bogachenko** [comment]
This issue is not from my list, but from the default list - 'uBlock filters – Ads'. The problem is in this rule `download.megaup.net##a img:not([src="images/main_logo_inverted.png"]):matches-css(height: /^([2-4]{1}[0-9]{2}(\.[0-9]+)?px|0px)$/):style(visibility: hidden !important;)`.
@Yuki2718 check out.
