### ISSUE TITLE
unknowncheats.me

### ISSUE THREAD

**Issue by gir489returns** [bogachenko/fuckfuckadblock#502]
### Basic information

**Check the link:** `https://www.unknowncheats.me/forum/helldivers-2-a/645905-server-updated.html`
**Category:** Anti-adblock
**Reported from:** USA

### User environment

**Browser:** Edge Version 126.0.2592.102 (Official build) (64-bit)
**Adblocker:** AdGuard Version 4.3.53
**Extensions:** Bitwarden, FoxyProxy, SponsorBlock for YouTube
**DNS:** Cloudflare Anti-Malware DoH.

### Additional message

At the bottom of the page, you will see this:

```
Enjoying our free services? We're committed to keeping your experience free and without restrictions, but please consider supporting us by disabling your adblocker or whitelisting our site.
```

You had patched this by blocking a javascript piece, but I think they started randomizing the name of it too.

**Comment by bogachenko** [comment]
@gir489returns hi.

I can't reproduce the issue; at first glance, nothing on the site has changed. Check if you have updated my list in the settings. **Clear cookies** in the browser, click on the Adguard icon in the Edge browser panel, and a menu with brief information about blocked ads and trackers will open. In this menu, find 'Open filtering log' and open it. A window will open, and on the left, there will be a green button labeled 'allowed', next to other buttons like 'blocked' - red, 'modified' - yellow, and so on. Click on 'allowed' and find the entry `https://www.unknowncheats.me/forum/clientscript/adv_teasers.js`. Is it green?

**Comment by gir489returns** [comment]
adv_teasers.js is red, it says AdGuard Base Filter is blocking it. It worked for like one day when you added it, but then stopped working. 

The only thing FuckFuckAdblock is blocking on the page is a giant rule that ends with:

`/scriptlet('ubo-set-constant.js', 'adsBlocked', 'noopFunc')`

I asked someone else to test in Firefox, and he said the ad still appears.

**Comment by bogachenko** [comment]
>adv_teasers.js is red, it says AdGuard Base Filter is blocking it

I'm sorry, but the problem is on your side. My [patch](https://github.com/bogachenko/fuckfuckadblock/commit/70fb016eae3574ec592d863dad5be5f7c9b88e29) allows this script and cannot be blocked by the built-in Adguard list. The site has not changed one iota, the notification code is the same, the same bait. If you add this rule - `@@|http*:*/adv_teasers.js$script`  to "Custom Filters", you will see this - the site has not changed.

Perhaps reinstalling will help solve your problem. Could you be using [the wrong subscription URL](https://github.com/bogachenko/fuckfuckadblock/wiki/Installation-instruction) for my sheet?
