### ISSUE TITLE
It's Allowing Connections to Facebook / Social Media tabs

### ISSUE THREAD

**Issue by throwaway282630101** [bogachenko/fuckfuckadblock#88]
Hi, there's an emergency with the "Fuck Fuckadblock" filter, it's allowing Facebook, Twitter and everything that's mostly blocked by AdGuard Social Media to allow those connections!

I'm using uBlock on Firefox to test, with AdGuard Social Media filter on.

This is the site I found the problem on:
https://9xbuddy.org/process?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DvCu0VJYMbiA

With Fuck Fuckadblock enabled, you can see the "Share on Facebook", Twitter and the social media buttons. But if you disable it and just leave AdGuard Social Media on it disables them from making a connection.

**Comment by bogachenko** [comment]
Hi, yes I know. You are welcome https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#known-issues
This is happening because I am abusing the `generichide` flag. It helps in the fight against bytes classes that site administrators use to display anti-adblock. At the moment, only I am working on the filter (And Adguard, for example, has a lot of hired people who can afford monitoring), and it is easier for me to add one filter than to monitor the addition of new bytes to classes by admins of different sites a hundred times.

As a temporary solution, you can add this to " My filters" - `@@*$generichide,domain=9xbuddy.org,badfilter`
But keep in mind if you unblock the anti-adblock by disabling the generichide flag on some site, then I will not help.

You can also read what ELSE you can do in your case, [also on the wiki](https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#known-issues), read the heading "To avoid problems with the Fuck Fuckadblock" under the heading "Known Issues"
