### ISSUE TITLE
vn-z.vn

### ISSUE THREAD

**Issue by Rusenche** [bogachenko/fuckfuckadblock#92]
### Basic information

**Check the link:** `https://vn-z.vn/threads/idm-6-38-build-14-25-11-2020-ung-dung-ho-tro-download-file-tot-nhat.4895/page-57`
**Category:** Breakage
**Reported from:** Bulgaria

### User environment

**Browser:** Centbrowser v.4.2.10.171 x86 portable
**Extension or program:** uBlock Origin v.1.31.2

### Additional message

I have the following problem with your filter: https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt

The problem is this. Almost everywhere in all sites where I block (for example `vn-z.vn##.adsbygoogle`) with Ublock origin v.1.31.2 after refreshing the page on the site appears the empty space occupied by `##.adsbygoogle`, but not is blocked. If I turn off your filter, the empty space disappears - `vn-z.vn##.adsbygoogle` is active.

I show two pictures.

Picture 1 shows when your filter is on:
http://store.picbg.net/pubpic/A9/C1/bbdb1d028e0ba9c1.png

Picture 2 shows when your filter is off:
http://store.picbg.net/pubpic/A7/F7/12739e5424c5a7f7.png

My request is to remove "adsbygoogle" from your filter so that there are no empty spaces on the sites.

**Comment by bogachenko** [comment]
Hi, I'm sorry, I can't remove this filter, because it can be used for the class byte (Administrators of some sites use classes in the html page to catch users who have adblock enabled, for antiadblock). This rule can help in the fight against anti-ad block. But like any thing, there are negative sides, in this case - empty spaces left from advertising on different sites.

My sheet has some more negative sides, you can [read about them here](https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#known-issues).

If you don't unsubscribe from the sheet after reading this wiki, then you can add this filter `vn-z.vn##[class].adsbygoogle` and it will remove empty spaces on the site.

You are welcome.
